// <auto-generated />
namespace SportData.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Culture_Entity_was_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Culture_Entity_was_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201703251644375_Culture_Entity_was_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
