// <auto-generated />
namespace SportData.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FootballPlayerChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FootballPlayerChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201704141921295_FootballPlayerChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
