//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете език.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG.
        /// </summary>
        public static string CurrentCulture {
            get {
                return ResourceManager.GetString("CurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основно меню.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Р.
        /// </summary>
        public static string LeagueRankingCaptionDraws {
            get {
                return ResourceManager.GetString("LeagueRankingCaptionDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГР.
        /// </summary>
        public static string LeagueRankingCaptionGoalDifference {
            get {
                return ResourceManager.GetString("LeagueRankingCaptionGoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З.
        /// </summary>
        public static string LeagueRankingCaptionLosses {
            get {
                return ResourceManager.GetString("LeagueRankingCaptionLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИМ.
        /// </summary>
        public static string LeagueRankingCaptionPlayedMatches {
            get {
                return ResourceManager.GetString("LeagueRankingCaptionPlayedMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т.
        /// </summary>
        public static string LeagueRankingCaptionPoints {
            get {
                return ResourceManager.GetString("LeagueRankingCaptionPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П.
        /// </summary>
        public static string LeagueRankingCaptionWins {
            get {
                return ResourceManager.GetString("LeagueRankingCaptionWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гост.
        /// </summary>
        public static string LeagueRankingTabAwayCaption {
            get {
                return ResourceManager.GetString("LeagueRankingTabAwayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класиране.
        /// </summary>
        public static string LeagueRankingTabCaption {
            get {
                return ResourceManager.GetString("LeagueRankingTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домакин.
        /// </summary>
        public static string LeagueRankingTabHomeCaption {
            get {
                return ResourceManager.GetString("LeagueRankingTabHomeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общо.
        /// </summary>
        public static string LeagueRankingTabOverallCaption {
            get {
                return ResourceManager.GetString("LeagueRankingTabOverallCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отбор.
        /// </summary>
        public static string LeagueRankingTeamCaption {
            get {
                return ResourceManager.GetString("LeagueRankingTeamCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локация.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        public static string NavigationAboutButton {
            get {
                return ResourceManager.GetString("NavigationAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админски панел.
        /// </summary>
        public static string NavigationAdminPanelButton {
            get {
                return ResourceManager.GetString("NavigationAdminPanelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string NavigationContactsButton {
            get {
                return ResourceManager.GetString("NavigationContactsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string NavigationHomeButton {
            get {
                return ResourceManager.GetString("NavigationHomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string NavigationLoginButton {
            get {
                return ResourceManager.GetString("NavigationLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Излез.
        /// </summary>
        public static string NavigationLogoffButton {
            get {
                return ResourceManager.GetString("NavigationLogoffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string NavigationRegisterButton {
            get {
                return ResourceManager.GetString("NavigationRegisterButton", resourceCulture);
            }
        }
    }
}
